#pragma once

typedef enum {
    POKEYSYNTH_MIDI_IN,
    POKEYSYNTH_AUDIO_OUT,
    POKEYSYNTH_CONTROL_CHANNELS,
    POKEYSYNTH_CONTROL_MONO_ARP1,
    POKEYSYNTH_CONTROL_MONO_ARP2,
    POKEYSYNTH_CONTROL_MONO_ARP3,
    POKEYSYNTH_CONTROL_MONO_ARP4,
    POKEYSYNTH_CONTROL_ARP_SPEED1,
    POKEYSYNTH_CONTROL_ARP_SPEED2,
    POKEYSYNTH_CONTROL_ARP_SPEED3,
    POKEYSYNTH_CONTROL_ARP_SPEED4,
    POKEYSYNTH_CONTROL_UPDATE_FREQ,
} PortIndex;
