name: Linux 64-bit
on: [workflow_dispatch]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-22.04]
          #os: [ubuntu-20.04, ubuntu-22.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: install packages
      run: sudo apt update && sudo apt install lv2-dev libfltk1.3-dev libxcursor-dev libxfixes-dev libxft-dev libxinerama-dev
    - name: make
      run: make -j`nproc`

    - name: Archive production artifacts
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: linux64-build-failure
        path: pokeysynth.lv2
